services:
  frontend:
    build:
      context: frontend
      args:
        FRONT_END_PORT: 3000
    ports:
      - 3000:3000

    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      args:
        NODE_PORT: 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

    networks:
      - express-mongo
      - react-express
    expose:
      - 5000

networks:
  react-express:
  express-mongo:
